apiVersion: v1
kind: Service
metadata:
  name: consulta-service
spec:
  type: NodePort
  selector:
    app: consulta
  ports:
    - name: consulta
      protocol: TCP
      #o nó recebe requisições nesta porta
      port: 6000
      #e direciona para esta porta do Pod
      targetPort: 6000
