apiVersion: v1
kind: Service
metadata:
  name: observacoes-service
spec:
  type: NodePort
  selector:
    app: observacoes
  ports:
    - name: observacoes
      protocol: TCP
      #o nó recebe requisições nesta porta
      port: 5000
      #e direciona para esta porta do Pod
      targetPort: 5000
